services:
  # Backend Service
  - type: web
    name: todo-backend-02250360
    env: node
    rootDir: backend
    plan: free
    envVars:
      - key: PORT
        value: 5000

  # Frontend Service
  - type: web
    name: todo-frontend-02250360
    env: static
    rootDir: frontend
    plan: free
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: todo-backend-02250360
          type: web
          property: host