services:
  # Backend Service
  - type: web
    name: be-todo
    env: docker
    repo: https://github.com/pelde684/dso101-cicd-assignment
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DB_HOST
        value: your-db-host
      - key: DB_USER
        value: your-db-user
      - key: DB_PASSWORD
        value: your-db-password
      - key: PORT
        value: "5000"

  # Frontend Service
  - type: web
    name: fe-todo
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: REACT_APP_API_URL
        value: https://be-todo.onrender.com