name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login ghcr.io -u pelde684 --password-stdin

      - name: Build Backend Image
        run: |
          docker build -t ghcr.io/pelde684/be-todo:latest ./todo-app/backend

      - name: Push Backend Image
        run: |
          docker push ghcr.io/pelde684/be-todo:latest

      - name: Build Frontend Image
        run: |
          docker build -t ghcr.io/pelde684/fe-todo:latest ./todo-app/frontend

      - name: Push Frontend Image
        run: |
          docker push ghcr.io/pelde684/fe-todo:latest

      - name: Trigger Render Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}